parameters:
    default_locale:           'es'
    dev_delivery_address:     '%env(string:DEV_DELIVERY_ADDRESS)%'
    google_analytics_active:  '%env(bool:GOOGLE_ANALYTICS_ACTIVE)%'
    google_analytics_api_key: '%env(string:GOOGLE_ANALYTICS_API_KEY)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    App\Controller\Admin\:
        resource: '../src/Controller/Admin'
        tags: ['controller.service_arguments', {name: 'sulu.context', context: 'admin'}]
    App\Controller\Website\:
        resource: '../src/Controller/Website'
        tags: ['controller.service_arguments', {name: 'sulu.context', context: 'website'}]
