parameters:
    website_locale:           '%env(string:WEBSITE_LOCALE)%'
    default_locale:           '%env(string:CR_LOCALE)%'
    cr_workspace:             '%env(string:CR_WORKSPACE)%'
    dev_delivery_address:     '%env(string:DEV_DELIVERY_ADDRESS)%'
    google_analytics_active:  '%env(bool:GOOGLE_ANALYTICS_ACTIVE)%'
    google_analytics_api_key: '%env(string:GOOGLE_ANALYTICS_API_KEY)%'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

services:
    _defaults:
        autowire:      true
        autoconfigure: true
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    App\Controller\Admin\:
        resource: '../src/Controller/Admin'
        tags: ['controller.service_arguments', {name: 'sulu.context', context: 'admin'}]
    App\Controller\Website\:
        resource: '../src/Controller/Website'
        tags: ['controller.service_arguments', {name: 'sulu.context', context: 'website'}]
    App\Manager\ContentRespositoryManager:
        arguments:
            - "@sulu_document_manager.document_manager"
            - "@sulu_document_manager.path_builder"
            - "@sulu_document_manager.document_inspector"
            - "%default_locale%"
            - "%cr_workspace%"
    App\Manager\MailManager:
        arguments:
            - "@mailer.mailer"
            - "%dev_delivery_address%"
